export const modelNames: Record<string, string> = {
  "qwen/qwen3-next-80b-a3b-thinking": "Qwen Qwen3 Next 80B A3B Thinking",
  "qwen/qwen3-next-80b-a3b-instruct": "Qwen Qwen3 Next 80B A3B Instruct",
  "meituan/longcat-flash-chat": "Meituan LongCat Flash Chat",
  "qwen/qwen-plus-2025-07-28": "Qwen Plus 0728",
  "qwen/qwen-plus-2025-07-28:thinking": "Qwen Plus 0728 (thinking)",
  "nvidia/nemotron-nano-9b-v2:free": "NVIDIA Nemotron Nano 9B V2",
  "nvidia/nemotron-nano-9b-v2": "NVIDIA Nemotron Nano 9B V2",
  "openrouter/sonoma-dusk-alpha": "Sonoma Dusk Alpha",
  "openrouter/sonoma-sky-alpha": "Sonoma Sky Alpha",
  "qwen/qwen3-max": "Qwen Qwen3 Max",
  "moonshotai/kimi-k2-0905": "MoonshotAI Kimi K2 0905",
  "bytedance/seed-oss-36b-instruct": "ByteDance Seed OSS 36B Instruct",
  "deepcogito/cogito-v2-preview-llama-109b-moe": "Cogito V2 Preview Llama 109B",
  "deepcogito/cogito-v2-preview-deepseek-671b": "Deep Cogito V2 Preview Deepseek 671B",
  "stepfun-ai/step3": "StepFun Step3",
  "qwen/qwen3-30b-a3b-thinking-2507": "Qwen Qwen3 30B A3B Thinking 2507",
  "x-ai/grok-code-fast-1": "xAI Grok Code Fast 1",
  "nousresearch/hermes-4-70b": "Nous Hermes 4 70B",
  "nousresearch/hermes-4-405b": "Nous Hermes 4 405B",
  "google/gemini-2.5-flash-image-preview": "Google Gemini 2.5 Flash Image Preview",
  "deepseek/deepseek-chat-v3.1:free": "DeepSeek V3.1",
  "deepseek/deepseek-chat-v3.1": "DeepSeek V3.1",
  "deepseek/deepseek-v3.1-base": "DeepSeek V3.1 Base",
  "openai/gpt-4o-audio-preview": "OpenAI GPT-4o Audio",
  "mistralai/mistral-medium-3.1": "Mistral Medium 3.1",
  "baidu/ernie-4.5-21b-a3b": "Baidu ERNIE 4.5 21B A3B",
  "baidu/ernie-4.5-vl-28b-a3b": "Baidu ERNIE 4.5 VL 28B A3B",
  "z-ai/glm-4.5v": "Z.AI GLM 4.5V",
  "ai21/jamba-mini-1.7": "AI21 Jamba Mini 1.7",
  "ai21/jamba-large-1.7": "AI21 Jamba Large 1.7",
  "openai/gpt-5-chat": "OpenAI GPT-5 Chat",
  "openai/gpt-5": "OpenAI GPT-5",
  "openai/gpt-5-mini": "OpenAI GPT-5 Mini",
  "openai/gpt-5-nano": "OpenAI GPT-5 Nano",
  "openai/gpt-oss-120b:free": "OpenAI gpt-oss-120b",
  "openai/gpt-oss-120b": "OpenAI gpt-oss-120b",
  "openai/gpt-oss-20b:free": "OpenAI gpt-oss-20b",
  "openai/gpt-oss-20b": "OpenAI gpt-oss-20b",
  "anthropic/claude-opus-4.1": "Anthropic Claude Opus 4.1",
  "mistralai/codestral-2508": "Mistral Codestral 2508",
  "qwen/qwen3-coder-30b-a3b-instruct": "Qwen Qwen3 Coder 30B A3B Instruct",
  "qwen/qwen3-30b-a3b-instruct-2507": "Qwen Qwen3 30B A3B Instruct 2507",
  "z-ai/glm-4.5": "Z.AI GLM 4.5",
  "z-ai/glm-4.5-air:free": "Z.AI GLM 4.5 Air",
  "z-ai/glm-4.5-air": "Z.AI GLM 4.5 Air",
  "qwen/qwen3-235b-a22b-thinking-2507": "Qwen Qwen3 235B A22B Thinking 2507",
  "z-ai/glm-4-32b": "Z.AI GLM 4 32B",
  "qwen/qwen3-coder:free": "Qwen Qwen3 Coder 480B A35B",
  "qwen/qwen3-coder": "Qwen Qwen3 Coder 480B A35B",
  "bytedance/ui-tars-1.5-7b": "ByteDance UI-TARS 7B",
  "google/gemini-2.5-flash-lite": "Google Gemini 2.5 Flash Lite",
  "qwen/qwen3-235b-a22b-2507": "Qwen Qwen3 235B A22B Instruct 2507",
  "switchpoint/router": "Switchpoint Router",
  "moonshotai/kimi-k2:free": "MoonshotAI Kimi K2 0711",
  "moonshotai/kimi-k2": "MoonshotAI Kimi K2 0711",
  "thudm/glm-4.1v-9b-thinking": "THUDM GLM 4.1V 9B Thinking",
  "mistralai/devstral-medium": "Mistral Devstral Medium",
  "mistralai/devstral-small": "Mistral Devstral Small 1.1",
  "cognitivecomputations/dolphin-mistral-24b-venice-edition:free": "Venice Uncensored",
  "x-ai/grok-4": "xAI Grok 4",
  "google/gemma-3n-e2b-it:free": "Google Gemma 3n 2B",
  "tencent/hunyuan-a13b-instruct:free": "Tencent Hunyuan A13B Instruct",
  "tencent/hunyuan-a13b-instruct": "Tencent Hunyuan A13B Instruct",
  "tngtech/deepseek-r1t2-chimera:free": "TNG DeepSeek R1T2 Chimera",
  "morph/morph-v3-large": "Morph V3 Large",
  "morph/morph-v3-fast": "Morph V3 Fast",
  "baidu/ernie-4.5-vl-424b-a47b": "Baidu ERNIE 4.5 VL 424B A47B",
  "baidu/ernie-4.5-300b-a47b": "Baidu ERNIE 4.5 300B A47B",
  "thedrummer/anubis-70b-v1.1": "TheDrummer Anubis 70B V1.1",
  "inception/mercury": "Inception Mercury",
  "mistralai/mistral-small-3.2-24b-instruct:free": "Mistral Small 3.2 24B",
  "mistralai/mistral-small-3.2-24b-instruct": "Mistral Small 3.2 24B",
  "minimax/minimax-m1": "MiniMax M1",
  "google/gemini-2.5-flash-lite-preview-06-17": "Google Gemini 2.5 Flash Lite Preview 06-17",
  "google/gemini-2.5-flash": "Google Gemini 2.5 Flash",
  "google/gemini-2.5-pro": "Google Gemini 2.5 Pro",
  "moonshotai/kimi-dev-72b:free": "MoonshotAI Kimi Dev 72B",
  "moonshotai/kimi-dev-72b": "MoonshotAI Kimi Dev 72B",
  "openai/o3-pro": "OpenAI o3 Pro",
  "x-ai/grok-3-mini": "xAI Grok 3 Mini",
  "x-ai/grok-3": "xAI Grok 3",
  "mistralai/magistral-small-2506": "Mistral Magistral Small 2506",
  "mistralai/magistral-medium-2506": "Mistral Magistral Medium 2506",
  "mistralai/magistral-medium-2506:thinking": "Mistral Magistral Medium 2506 (thinking)",
  "google/gemini-2.5-pro-preview": "Google Gemini 2.5 Pro Preview 06-05",
  "deepseek/deepseek-r1-0528-qwen3-8b:free": "Deepseek R1 0528 Qwen3 8B",
  "deepseek/deepseek-r1-0528-qwen3-8b": "Deepseek R1 0528 Qwen3 8B",
  "deepseek/deepseek-r1-0528:free": "DeepSeek R1 0528",
  "deepseek/deepseek-r1-0528": "DeepSeek R1 0528",
  "anthropic/claude-opus-4": "Anthropic Claude Opus 4",
  "anthropic/claude-sonnet-4": "Anthropic Claude Sonnet 4",
  "mistralai/devstral-small-2505:free": "Mistral Devstral Small 2505",
  "mistralai/devstral-small-2505": "Mistral Devstral Small 2505",
  "google/gemma-3n-e4b-it:free": "Google Gemma 3n 4B",
  "google/gemma-3n-e4b-it": "Google Gemma 3n 4B",
  "openai/codex-mini": "OpenAI Codex Mini",
  "meta-llama/llama-3.3-8b-instruct:free": "Meta Llama 3.3 8B Instruct",
  "nousresearch/deephermes-3-mistral-24b-preview": "Nous DeepHermes 3 Mistral 24B Preview",
  "mistralai/mistral-medium-3": "Mistral Medium 3",
  "google/gemini-2.5-pro-preview-05-06": "Google Gemini 2.5 Pro Preview 05-06",
  "arcee-ai/spotlight": "Arcee AI Spotlight",
  "arcee-ai/maestro-reasoning": "Arcee AI Maestro Reasoning",
  "arcee-ai/virtuoso-large": "Arcee AI Virtuoso Large",
  "arcee-ai/coder-large": "Arcee AI Coder Large",
  "microsoft/phi-4-reasoning-plus": "Microsoft Phi 4 Reasoning Plus",
  "inception/mercury-coder": "Inception Mercury Coder",
  "qwen/qwen3-4b:free": "Qwen Qwen3 4B",
  "deepseek/deepseek-prover-v2": "DeepSeek Prover V2",
  "meta-llama/llama-guard-4-12b": "Meta Llama Guard 4 12B",
  "qwen/qwen3-30b-a3b:free": "Qwen Qwen3 30B A3B",
  "qwen/qwen3-30b-a3b": "Qwen Qwen3 30B A3B",
  "qwen/qwen3-8b:free": "Qwen Qwen3 8B",
  "qwen/qwen3-8b": "Qwen Qwen3 8B",
  "qwen/qwen3-14b:free": "Qwen Qwen3 14B",
  "qwen/qwen3-14b": "Qwen Qwen3 14B",
  "qwen/qwen3-32b": "Qwen Qwen3 32B",
  "qwen/qwen3-235b-a22b:free": "Qwen Qwen3 235B A22B",
  "qwen/qwen3-235b-a22b": "Qwen Qwen3 235B A22B",
  "tngtech/deepseek-r1t-chimera:free": "TNG DeepSeek R1T Chimera",
  "tngtech/deepseek-r1t-chimera": "TNG DeepSeek R1T Chimera",
  "microsoft/mai-ds-r1:free": "Microsoft MAI DS R1",
  "microsoft/mai-ds-r1": "Microsoft MAI DS R1",
  "thudm/glm-z1-32b": "THUDM GLM Z1 32B",
  "thudm/glm-4-32b": "THUDM GLM 4 32B",
  "openai/o4-mini-high": "OpenAI o4 Mini High",
  "openai/o3": "OpenAI o3",
  "openai/o4-mini": "OpenAI o4 Mini",
  "shisa-ai/shisa-v2-llama3.3-70b:free": "Shisa AI Shisa V2 Llama 3.3 70B",
  "shisa-ai/shisa-v2-llama3.3-70b": "Shisa AI Shisa V2 Llama 3.3 70B",
  "openai/gpt-4.1": "OpenAI GPT-4.1",
  "openai/gpt-4.1-mini": "OpenAI GPT-4.1 Mini",
  "openai/gpt-4.1-nano": "OpenAI GPT-4.1 Nano",
  "eleutherai/llemma_7b": "EleutherAI Llemma 7b",
  "alfredpros/codellama-7b-instruct-solidity": "AlfredPros CodeLLaMa 7B Instruct Solidity",
  "arliai/qwq-32b-arliai-rpr-v1:free": "ArliAI QwQ 32B RpR v1",
  "arliai/qwq-32b-arliai-rpr-v1": "ArliAI QwQ 32B RpR v1",
  "agentica-org/deepcoder-14b-preview:free": "Agentica Deepcoder 14B Preview",
  "agentica-org/deepcoder-14b-preview": "Agentica Deepcoder 14B Preview",
  "moonshotai/kimi-vl-a3b-thinking:free": "MoonshotAI Kimi VL A3B Thinking",
  "moonshotai/kimi-vl-a3b-thinking": "MoonshotAI Kimi VL A3B Thinking",
  "x-ai/grok-3-mini-beta": "xAI Grok 3 Mini Beta",
  "x-ai/grok-3-beta": "xAI Grok 3 Beta",
  "nvidia/llama-3.1-nemotron-ultra-253b-v1:free": "NVIDIA Llama 3.1 Nemotron Ultra 253B v1",
  "nvidia/llama-3.1-nemotron-ultra-253b-v1": "NVIDIA Llama 3.1 Nemotron Ultra 253B v1",
  "meta-llama/llama-4-maverick:free": "Meta Llama 4 Maverick",
  "meta-llama/llama-4-maverick": "Meta Llama 4 Maverick",
  "meta-llama/llama-4-scout:free": "Meta Llama 4 Scout",
  "meta-llama/llama-4-scout": "Meta Llama 4 Scout",
  "allenai/molmo-7b-d": "AllenAI Molmo 7B D",
  "qwen/qwen2.5-vl-32b-instruct:free": "Qwen Qwen2.5 VL 32B Instruct",
  "qwen/qwen2.5-vl-32b-instruct": "Qwen Qwen2.5 VL 32B Instruct",
  "deepseek/deepseek-chat-v3-0324:free": "DeepSeek V3 0324",
  "deepseek/deepseek-chat-v3-0324": "DeepSeek V3 0324",
  "openai/o1-pro": "OpenAI o1-pro",
  "mistralai/mistral-small-3.1-24b-instruct:free": "Mistral Small 3.1 24B",
  "mistralai/mistral-small-3.1-24b-instruct": "Mistral Small 3.1 24B",
  "allenai/olmo-2-0325-32b-instruct": "AllenAI Olmo 2 32B Instruct",
  "google/gemma-3-4b-it:free": "Google Gemma 3 4B",
  "google/gemma-3-4b-it": "Google Gemma 3 4B",
  "google/gemma-3-12b-it:free": "Google Gemma 3 12B",
  "google/gemma-3-12b-it": "Google Gemma 3 12B",
  "cohere/command-a": "Cohere Command A",
  "openai/gpt-4o-mini-search-preview": "OpenAI GPT-4o-mini Search Preview",
  "openai/gpt-4o-search-preview": "OpenAI GPT-4o Search Preview",
  "rekaai/reka-flash-3:free": "Reka Flash 3",
  "google/gemma-3-27b-it:free": "Google Gemma 3 27B",
  "google/gemma-3-27b-it": "Google Gemma 3 27B",
  "thedrummer/anubis-pro-105b-v1": "TheDrummer Anubis Pro 105B V1",
  "thedrummer/skyfall-36b-v2": "TheDrummer Skyfall 36B V2",
  "microsoft/phi-4-multimodal-instruct": "Microsoft Phi 4 Multimodal Instruct",
  "perplexity/sonar-reasoning-pro": "Perplexity Sonar Reasoning Pro",
  "perplexity/sonar-pro": "Perplexity Sonar Pro",
  "perplexity/sonar-deep-research": "Perplexity Sonar Deep Research",
  "qwen/qwq-32b:free": "Qwen QwQ 32B",
  "qwen/qwq-32b": "Qwen QwQ 32B",
  "nousresearch/deephermes-3-llama-3-8b-preview:free": "Nous DeepHermes 3 Llama 3 8B Preview",
  "google/gemini-2.0-flash-lite-001": "Google Gemini 2.0 Flash Lite",
  "anthropic/claude-3.7-sonnet": "Anthropic Claude 3.7 Sonnet",
  "anthropic/claude-3.7-sonnet:thinking": "Anthropic Claude 3.7 Sonnet (thinking)",
  "perplexity/r1-1776": "Perplexity R1 1776",
  "mistralai/mistral-saba": "Mistral Saba",
  "cognitivecomputations/dolphin3.0-r1-mistral-24b:free": "Dolphin3.0 R1 Mistral 24B",
  "cognitivecomputations/dolphin3.0-r1-mistral-24b": "Dolphin3.0 R1 Mistral 24B",
  "cognitivecomputations/dolphin3.0-mistral-24b:free": "Dolphin3.0 Mistral 24B",
  "cognitivecomputations/dolphin3.0-mistral-24b": "Dolphin3.0 Mistral 24B",
  "meta-llama/llama-guard-3-8b": "Llama Guard 3 8B",
  "openai/o3-mini-high": "OpenAI o3 Mini High",
  "deepseek/deepseek-r1-distill-llama-8b": "DeepSeek R1 Distill Llama 8B",
  "google/gemini-2.0-flash-001": "Google Gemini 2.0 Flash",
  "qwen/qwen-vl-plus": "Qwen VL Plus",
  "aion-labs/aion-1.0": "AionLabs Aion-1.0",
  "aion-labs/aion-1.0-mini": "AionLabs Aion-1.0-Mini",
  "aion-labs/aion-rp-llama-3.1-8b": "AionLabs Aion-RP 1.0 (8B)",
  "qwen/qwen-vl-max": "Qwen VL Max",
  "qwen/qwen-turbo": "Qwen Qwen-Turbo",
  "qwen/qwen2.5-vl-72b-instruct:free": "Qwen Qwen2.5 VL 72B Instruct",
  "qwen/qwen2.5-vl-72b-instruct": "Qwen Qwen2.5 VL 72B Instruct",
  "qwen/qwen-plus": "Qwen Qwen-Plus",
  "qwen/qwen-max": "Qwen Qwen-Max",
  "openai/o3-mini": "OpenAI o3 Mini",
  "mistralai/mistral-small-24b-instruct-2501:free": "Mistral Small 3",
  "mistralai/mistral-small-24b-instruct-2501": "Mistral Small 3",
  "deepseek/deepseek-r1-distill-qwen-32b": "DeepSeek R1 Distill Qwen 32B",
  "deepseek/deepseek-r1-distill-qwen-14b:free": "DeepSeek R1 Distill Qwen 14B",
  "deepseek/deepseek-r1-distill-qwen-14b": "DeepSeek R1 Distill Qwen 14B",
  "perplexity/sonar-reasoning": "Perplexity Sonar Reasoning",
  "perplexity/sonar": "Perplexity Sonar",
  "liquid/lfm-7b": "Liquid LFM 7B",
  "liquid/lfm-3b": "Liquid LFM 3B",
  "deepseek/deepseek-r1-distill-llama-70b:free": "DeepSeek R1 Distill Llama 70B",
  "deepseek/deepseek-r1-distill-llama-70b": "DeepSeek R1 Distill Llama 70B",
  "deepseek/deepseek-r1:free": "DeepSeek R1",
  "deepseek/deepseek-r1": "DeepSeek R1",
  "minimax/minimax-01": "MiniMax MiniMax-01",
  "mistralai/codestral-2501": "Mistral Codestral 2501",
  "microsoft/phi-4": "Microsoft Phi 4",
  "deepseek/deepseek-chat": "DeepSeek V3",
  "sao10k/l3.3-euryale-70b": "Sao10K Llama 3.3 Euryale 70B",
  "openai/o1": "OpenAI o1",
  "x-ai/grok-2-vision-1212": "xAI Grok 2 Vision 1212",
  "x-ai/grok-2-1212": "xAI Grok 2 1212",
  "cohere/command-r7b-12-2024": "Cohere Command R7B (12-2024)",
  "google/gemini-2.0-flash-exp:free": "Google Gemini 2.0 Flash Experimental",
  "meta-llama/llama-3.3-70b-instruct:free": "Meta Llama 3.3 70B Instruct",
  "meta-llama/llama-3.3-70b-instruct": "Meta Llama 3.3 70B Instruct",
  "amazon/nova-lite-v1": "Amazon Nova Lite 1.0",
  "amazon/nova-micro-v1": "Amazon Nova Micro 1.0",
  "amazon/nova-pro-v1": "Amazon Nova Pro 1.0",
  "qwen/qwq-32b-preview": "Qwen QwQ 32B Preview",
  "openai/gpt-4o-2024-11-20": "OpenAI GPT-4o (2024-11-20)",
  "mistralai/mistral-large-2411": "Mistral Large 2411",
  "mistralai/mistral-large-2407": "Mistral Large 2407",
  "mistralai/pixtral-large-2411": "Mistral Pixtral Large 2411",
  "qwen/qwen-2.5-coder-32b-instruct:free": "Qwen2.5 Coder 32B Instruct",
  "qwen/qwen-2.5-coder-32b-instruct": "Qwen2.5 Coder 32B Instruct",
  "raifle/sorcererlm-8x22b": "SorcererLM 8x22B",
  "thedrummer/unslopnemo-12b": "TheDrummer UnslopNemo 12B",
  "anthropic/claude-3.5-haiku": "Anthropic Claude 3.5 Haiku",
  "anthropic/claude-3.5-haiku-20241022": "Anthropic Claude 3.5 Haiku (2024-10-22)",
  "anthracite-org/magnum-v4-72b": "Magnum v4 72B",
  "anthropic/claude-3.5-sonnet": "Anthropic Claude 3.5 Sonnet",
  "mistralai/ministral-8b": "Mistral Ministral 8B",
  "mistralai/ministral-3b": "Mistral Ministral 3B",
  "qwen/qwen-2.5-7b-instruct": "Qwen2.5 7B Instruct",
  "nvidia/llama-3.1-nemotron-70b-instruct": "NVIDIA Llama 3.1 Nemotron 70B Instruct",
  "inflection/inflection-3-productivity": "Inflection 3 Productivity",
  "inflection/inflection-3-pi": "Inflection 3 Pi",
  "google/gemini-flash-1.5-8b": "Google Gemini 1.5 Flash 8B",
  "thedrummer/rocinante-12b": "TheDrummer Rocinante 12B",
  "anthracite-org/magnum-v2-72b": "Magnum v2 72B",
  "meta-llama/llama-3.2-3b-instruct:free": "Meta Llama 3.2 3B Instruct",
  "meta-llama/llama-3.2-3b-instruct": "Meta Llama 3.2 3B Instruct",
  "meta-llama/llama-3.2-1b-instruct": "Meta Llama 3.2 1B Instruct",
  "meta-llama/llama-3.2-90b-vision-instruct": "Meta Llama 3.2 90B Vision Instruct",
  "meta-llama/llama-3.2-11b-vision-instruct": "Meta Llama 3.2 11B Vision Instruct",
  "qwen/qwen-2.5-72b-instruct:free": "Qwen2.5 72B Instruct",
  "qwen/qwen-2.5-72b-instruct": "Qwen2.5 72B Instruct",
  "neversleep/llama-3.1-lumimaid-8b": "NeverSleep Lumimaid v0.2 8B",
  "openai/o1-mini": "OpenAI o1-mini",
  "openai/o1-mini-2024-09-12": "OpenAI o1-mini (2024-09-12)",
  "mistralai/pixtral-12b": "Mistral Pixtral 12B",
  "cohere/command-r-plus-08-2024": "Cohere Command R+ (08-2024)",
  "cohere/command-r-08-2024": "Cohere Command R (08-2024)",
  "qwen/qwen-2.5-vl-7b-instruct": "Qwen Qwen2.5-VL 7B Instruct",
  "sao10k/l3.1-euryale-70b": "Sao10K Llama 3.1 Euryale 70B v2.2",
  "microsoft/phi-3.5-mini-128k-instruct": "Microsoft Phi-3.5 Mini 128K Instruct",
  "nousresearch/hermes-3-llama-3.1-70b": "Nous Hermes 3 70B Instruct",
  "nousresearch/hermes-3-llama-3.1-405b": "Nous Hermes 3 405B Instruct",
  "openai/chatgpt-4o-latest": "OpenAI ChatGPT-4o",
  "sao10k/l3-lunaris-8b": "Sao10K Llama 3 8B Lunaris",
  "openai/gpt-4o-2024-08-06": "OpenAI GPT-4o (2024-08-06)",
  "meta-llama/llama-3.1-405b": "Meta Llama 3.1 405B (base)",
  "meta-llama/llama-3.1-8b-instruct": "Meta Llama 3.1 8B Instruct",
  "meta-llama/llama-3.1-405b-instruct:free": "Meta Llama 3.1 405B Instruct",
  "meta-llama/llama-3.1-405b-instruct": "Meta Llama 3.1 405B Instruct",
  "meta-llama/llama-3.1-70b-instruct": "Meta Llama 3.1 70B Instruct",
  "mistralai/mistral-nemo:free": "Mistral Nemo",
  "mistralai/mistral-nemo": "Mistral Nemo",
  "openai/gpt-4o-mini": "OpenAI GPT-4o-mini",
  "openai/gpt-4o-mini-2024-07-18": "OpenAI GPT-4o-mini (2024-07-18)",
  "google/gemma-2-27b-it": "Google Gemma 2 27B",
  "google/gemma-2-9b-it:free": "Google Gemma 2 9B",
  "google/gemma-2-9b-it": "Google Gemma 2 9B",
  "anthropic/claude-3.5-sonnet-20240620": "Anthropic Claude 3.5 Sonnet (2024-06-20)",
  "sao10k/l3-euryale-70b": "Sao10k Llama 3 Euryale 70B v2.1",
  "cognitivecomputations/dolphin-mixtral-8x22b": "Dolphin 2.9.2 Mixtral 8x22B 🐬",
  "mistralai/mistral-7b-instruct:free": "Mistral 7B Instruct",
  "mistralai/mistral-7b-instruct": "Mistral 7B Instruct",
  "nousresearch/hermes-2-pro-llama-3-8b": "NousResearch Hermes 2 Pro - Llama-3 8B",
  "mistralai/mistral-7b-instruct-v0.3": "Mistral 7B Instruct v0.3",
  "microsoft/phi-3-mini-128k-instruct": "Microsoft Phi-3 Mini 128K Instruct",
  "microsoft/phi-3-medium-128k-instruct": "Microsoft Phi-3 Medium 128K Instruct",
  "neversleep/llama-3-lumimaid-70b": "NeverSleep Llama 3 Lumimaid 70B",
  "google/gemini-flash-1.5": "Google Gemini 1.5 Flash",
  "openai/gpt-4o": "OpenAI GPT-4o",
  "openai/gpt-4o:extended": "OpenAI GPT-4o (extended)",
  "meta-llama/llama-guard-2-8b": "Meta LlamaGuard 2 8B",
  "openai/gpt-4o-2024-05-13": "OpenAI GPT-4o (2024-05-13)",
  "meta-llama/llama-3-8b-instruct": "Meta Llama 3 8B Instruct",
  "meta-llama/llama-3-70b-instruct": "Meta Llama 3 70B Instruct",
  "mistralai/mixtral-8x22b-instruct": "Mistral Mixtral 8x22B Instruct",
  "microsoft/wizardlm-2-8x22b": "WizardLM-2 8x22B",
  "google/gemini-pro-1.5": "Google Gemini 1.5 Pro",
  "openai/gpt-4-turbo": "OpenAI GPT-4 Turbo",
  "cohere/command-r-plus": "Cohere Command R+",
  "cohere/command-r-plus-04-2024": "Cohere Command R+ (04-2024)",
  "sophosympatheia/midnight-rose-70b": "Midnight Rose 70B",
  "cohere/command": "Cohere Command",
  "cohere/command-r": "Cohere Command R",
  "anthropic/claude-3-haiku": "Anthropic Claude 3 Haiku",
  "anthropic/claude-3-opus": "Anthropic Claude 3 Opus",
  "cohere/command-r-03-2024": "Cohere Command R (03-2024)",
  "mistralai/mistral-large": "Mistral Large",
  "openai/gpt-3.5-turbo-0613": "OpenAI GPT-3.5 Turbo (older v0613)",
  "openai/gpt-4-turbo-preview": "OpenAI GPT-4 Turbo Preview",
  "mistralai/mistral-small": "Mistral Small",
  "mistralai/mistral-tiny": "Mistral Tiny",
  "mistralai/mixtral-8x7b-instruct": "Mistral Mixtral 8x7B Instruct",
  "neversleep/noromaid-20b": "Noromaid 20B",
  "alpindale/goliath-120b": "Goliath 120B",
  "openrouter/auto": "Auto Router",
  "openai/gpt-4-1106-preview": "OpenAI GPT-4 Turbo (older v1106)",
  "openai/gpt-3.5-turbo-instruct": "OpenAI GPT-3.5 Turbo Instruct",
  "mistralai/mistral-7b-instruct-v0.1": "Mistral 7B Instruct v0.1",
  "openai/gpt-3.5-turbo-16k": "OpenAI GPT-3.5 Turbo 16k",
  "mancer/weaver": "Mancer Weaver (alpha)",
  "undi95/remm-slerp-l2-13b": "ReMM SLERP 13B",
  "gryphe/mythomax-l2-13b": "MythoMax 13B",
  "openai/gpt-3.5-turbo": "OpenAI GPT-3.5 Turbo",
  "openai/gpt-4": "OpenAI GPT-4",
  "openai/gpt-4-0314": "OpenAI GPT-4 (older v0314)"
};

export const getModelDisplayName = (modelId: string): string => {
  return modelNames[modelId] || modelId;
};