// A small list of random words for the game
export const words = [
  "ELEPHANT",
  "SUNSHINE",
  "RAINBOW",
  "BUTTERFLY",
  "MOUNTAIN",
  "OCEAN",
  "GALAXY",
  "WHISPER",
  "BREEZE",
  "DIAMOND",
  "STARDUST",
  "MEADOW",
  "WILDFLOWER",
  "HORIZON",
  "JOURNEY",
  "FEATHER",
  "TWILIGHT",
  "CANYON",
  "WONDER",
  "FOREST",
  "THUNDER",
  "LIGHTNING",
  "LANTERN",
  "CLOUD",
  "CRYSTAL",
  "HARMONY",
  "MIRACLE",
  "SHADOW",
  "TREASURE",
  "ECHO",
  "SNOWFLAKE",
  "COMET",
  "WILDERNESS",
  "FREEDOM",
  "NIGHTFALL",
  "FANTASY",
  "ADVENTURE",
  "SERENITY",
  "DREAM",
  "GLOW",
  "RIVER",
  "VISTA",
  "WISH",
  "PEBBLE",
  "MOONLIGHT",
  "HEARTBEAT",
  "WANDERLUST",
  "STARLIGHT",
  "CRESCENT",
  "WATERFALL",
  "CITADEL",
];

export const getRandomWord = () => {
  return words[Math.floor(Math.random() * words.length)];
};